services:
  mysqldb:
    image: mysql
    restart: on-failure
#    hostname: "todoappdb"
    healthcheck:
      test: "exit 0"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: my-password
    command:
      - --skip-log-bin
    ports:
      - "3306:3306"
    volumes:
      - mysqlvol:/var/lib/mysql

  todobackend:
    image: todo-app-backend
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/todo_db

  ui:
    image: maeddes/tmpfrontend
    ports:
      - "5137:5137"

volumes:
  mysqlvol:
    name: mysqlvol