services:
  postgresdb:
    image: mysql
    restart: on-failure
#    hostname: "todoappdb"
    healthcheck:
      test: "exit 0"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: my-password
    command:
      - --skip-log-bin
    ports:
      - "3306:3306"

  todobackend:
    image: todo-app-backend
    depends_on:
      postgresdb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://postgresdb:3306/todo_db

#  ui:
#    image: todo-app-ui
#    ports:
#      - "5137:5137"